### PR TITLE
Fix sign in on Firefox with this one weird trick!

### PR DESCRIPTION
**Pull request by lyleschemmerling**
# Fix sign in on Firefox with this one weird trick!

## Description

Changes our sign-in method to "with popup" which should work better on Firefox and Safari for the time being.

## Related Issue

- [Best Practices](https://firebase.google.com/docs/auth/web/redirect-best-practices)

## Acceptance Criteria

- [ ] Can sign in to the webapp

## Type of Changes

- bug fix

### Before

Firefox signin was broken

### After

Firefox sign in should work

## Testing Steps / QA Criteria

Please try to log in using a non-Chromium browser such as Firefox or Safari

### CODE REVIEW

**Comment by lyleschemmerling** [comment]
I'll want to fix this proper as the popup is not a good mobile experience but I don't know how to do that yet 😿

**Review by djtaylor8 — APPROVED** [review]
Thanks for doing this!

**Review by chungleee — APPROVED** [review]
As a fellow FF user, thank you 🙏

**Review by MiliMade — APPROVED** [review]

**Review by g-lee2 — APPROVED** [review]

**Review by RachaelSkye — APPROVED** [review]
Nice! This one weird trick worked just as expected when I tried it out. :shipit:

**Pull request merged**
