### PR TITLE
add navigate-with-navLink

### LINKED ISSUE #3: 3. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouter.com/en/6.14.2/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by amandaguan-ag**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

This PR adds change from navigation element from <a> to <NavLink> and the links all function as expected.

## Related Issue

closes #3 

## Acceptance Criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Type of Changes

Fix navigation feature

### Before

Link for List and Manage List doesn't work

### After
image

image

## Testing Steps / QA Criteria
1. From your terminal, enter: git checkout ag-lc-navigate-with-navlink
2. From your terminal, enter: npm start
3. Click on navigation links

### CODE REVIEW

**Review by g-lee2 — APPROVED** [review]
Looks good!

**Review by MiliMade — APPROVED** [review]

**Review by djtaylor8 — APPROVED** [review]
Nice job, @amandaguan-ag and @chungleee! Minor pull request nit moving forward - it can be helpful to add the issue number and a more descriptive title. Definitely not a big deal now, but as the issues start adding up, this is useful to help track what exactly has been done.

**Review by RachaelSkye — APPROVED** [review]
This looks great! We've got nav links that all work as expected. :shipit:

**Review by lyleschemmerling — APPROVED** [review]
hey look I can navigate!

**Review by chungleee — APPROVED** [review]

**Pull request merged**
